### ISSUE TITLE
Non-critical; OnRemoved is not a valid function (nil)

### ISSUE THREAD

**Issue by Sezei** [Cosmental/Social-Chat#12]
[SocialChat.Environments.Client](https://github.com/Cosmental/Social-Chat/blob/main/src/ServerScriptService/MainModule/SocialChat/Environments/Client/init.lua) - Line 1067; `ChatSystemTags[BubbleGarbage.EffectName].OnRemoved(BubbleGarbage.Effect)` will error because of effects not existing (hence having .OnRemoved attempt to call a nil value). Perhaps add a check such as this?

```lua
if ChatSystemTags[BubbleGarbage.EffectName] and ChatSystemTags[BubbleGarbage.EffectName].OnRemoved then
    ChatSystemTags[BubbleGarbage.EffectName].OnRemoved(BubbleGarbage.Effect);
end
```

**Comment by Cosmental** [comment]
This should be fixed now, thanks for your report!
