### ISSUE TITLE
hello . In large  display there are this problem , how can i fix it? and how i can add more tags for other people

### ISSUE THREAD

**Issue by firino1** [Cosmental/Social-Chat#13]
![изображение_2022-09-10_174630462](https://user-images.githubusercontent.com/113249866/189488552-fa41e981-4238-43b9-b3f5-60eda8be2fca.png)

**Comment by Cosmental** [comment]
There is a configuration for TextBox fontSize in the ``ChatSystemConfigurations`` module. This is done mostly for visual appearances but you can adjust this to however you see fit!
![image](https://user-images.githubusercontent.com/52884117/189489485-bc9dc47d-0720-44d9-aab7-ae13765deb67.png)

As for chat tags, you should be able to find a ``Tags`` module inside of the **"Server"** folder and you should be able to add new roles from there using the available configuration data.

**Comment by firino1** [comment]
i changed it to 25 , but there is bug , the size has not changed and the input bar has moved. In Tags module i made smth like this , it don’t working , mb you can help me
![image](https://user-images.githubusercontent.com/113249866/189490101-9d4c27bb-30cf-4f77-b65f-8403765a0d7b.png)
![image](https://user-images.githubusercontent.com/113249866/189490112-d3174e3c-6fda-4183-b7fc-f11a34984668.png)
![image](https://user-images.githubusercontent.com/113249866/189490129-2e5d420e-07a9-4f91-8ea9-2945d69778e2.png)

**Comment by Cosmental** [comment]
This is definitely unintentional! I'll get right to fixing it in a bit!

**Comment by firino1** [comment]
ok i think i helped you , so you will be fix tags and chat box size right?

**Comment by firino1** [comment]
and im not understand in this point , for custom emoji (not a gif ) i need just set asset id into script?
