### ISSUE TITLE
Chat bubbles rarely does not display

### ISSUE THREAD

**Issue by ghost** [Cosmental/Social-Chat#2]
**Description**
The chat bubble rarely displays and is completely missing. It is expected to show but currently rarely produces this issue upon joining. 

*Perhaps there's something with the timing of players joining at the same time?*

**Reproduction**
Unknown

**Attachments**
<img width="1440" alt="first_occurence" src="https://user-images.githubusercontent.com/54335833/184455853-c1c2a2d5-d8d7-4d24-868f-51379f4f76bc.png">

**Comment by Cosmental** [comment]
**Issue:** ChatBubbles would require initialization upon a character being created. Joining at the same time as another player would cause ``.PlayerAdded`` to not fire at all. Using the ``:GetPlayers()`` method did not work either.

**Solution:** ChatBubbles now register upon the method being called. This now serves an additional purpose for NPCs who use the chat system as well.
