### ISSUE TITLE
Text is all jumbled.

### ISSUE THREAD

**Issue by ItIsRoxy** [Cosmental/Social-Chat#3]
The text in the chat appears all jumbled, letters are randomly thrown around and even overlapping.
![image](https://user-images.githubusercontent.com/111158621/184455533-1655612b-8077-432e-9433-51814879fdbc.png)

**Comment by Cosmental** [comment]
Debbuing has been implemented. Pending a second playtest to fully analyze the problem.

**Comment by Cosmental** [comment]
**Issue:** Method ``GetTextSize`` was being used on the WordFrame rather than the actual container.

**Solution:** ``GetTextSize`` now respects it's main container and applies sizing logic to the container rather than the grapheme's wordFrame.
