### ISSUE TITLE
Making Admin Commands

### ISSUE THREAD

**Issue by CalypsoGames01** [Cosmental/Social-Chat#6]
Hello im **DragonDarkVader** a **Roblox Developer** with **1.5 years** of Developing Experience

I'd like to add a Request on Admin Commands, I don't care if it would take long. As long as it's complete

**Important Commands**
1. Ban
2. Kick
3. Perm Ban
4. UnBan
5. Warn

**Fun Commands**
1.Fly
2. UnFly
3. Shutdown
4. AddRole
5. RemoveRole
6. AddAdmin/Mod
7. RemoveAdmin/Mod
8. Countdown

**Trolling Commands**
1.Fling
2.Blind
3.Spectate
4.Fire

**Comment by Cosmental** [comment]
Admin commands can be written by you using the ``SocialChat.PlayerChatted`` method within the API.

**Comment by CalypsoGames01** [comment]
Thanks you cosmental, But how did you find my Gmail account?

**Comment by Cosmental** [comment]
GitHub automatically sends you email updates when someone replies to your Github Post.

**Comment by CalypsoGames01** [comment]
Well, Techniquely this is my account I got my other account "CalypsoGames".
So Basically this is not my account but I used it

**Comment by CalypsoGames01** [comment]
I mean, NOT my account
