### ISSUE TITLE
Special Characters are Broken

### ISSUE THREAD

**Issue by ghost** [Cosmental/Social-Chat#8]
Special character, such as those for languages like Japanese don't render correctly.

SocialChat:
![7ACBE18D-8E0A-403E-9D43-BA0C104B0623](https://user-images.githubusercontent.com/112315565/187066514-545beeee-a951-4e44-aa27-51e3088c60c6.png)

Roblox Chat:
![8672824B-4558-455D-BADA-DE26B8A5425D](https://user-images.githubusercontent.com/112315565/187066531-3b44540c-3e05-477d-97e9-52336d837781.png)

**Comment by Cosmental** [comment]
This should be fixed within the next SocialChat update!
![image](https://user-images.githubusercontent.com/52884117/187075000-c84949ba-6c4d-4b32-a343-bc67361fbae9.png)
